In [ ]:
##00. Pytorch Fundamentals
#Resource Book: https://www.learnpytorch.io/

In [ ]:
print("Hello I'm starting to learn Pytorch")

Hello I'm starting to learn Pytorch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


#Introduction to tensors
###Creating Tensors




In [ ]:
#scalar
scalar=torch.tensor(7)
scalar
#Pytorch tensors are used using torch.Tensor() ->https://pytorch.org/docs/stable/tensors.html

tensor(7)

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
#Number of dimensions
vector.ndim

1

In [ ]:
#Shape
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

###Random Tensors

These are important because neural networks start with tensors with random numbers and then adjust those to better represent the data.


'Start with random numbers -> look at data -> update random numbers -> update random numbers'

Torch random numbers https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand

In [ ]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.2151, 0.0620, 0.4310, 0.8573],
        [0.0117, 0.7565, 0.6311, 0.3004],
        [0.3516, 0.8736, 0.8507, 0.8562]])

In [ ]:
#Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #Height Width, color channels 3 (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones


In [ ]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
zeros = torch.ones(size=(3,4))
zeros

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Creating a arange of tensors-like

In [ ]:
#torch.arange(start, stop. step)
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

It has to do with precision in computer science. Most used are 16bits and 32bits.

**Note:**

More bits = More precisin but slower

Less Bits = Less Precision but faster



Dtype is one of the 3 big errors of pytorch & Deep learning

The others two: tensors not right shape or on the right device.

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0 ,9.0],
                               dtype=None, #How much detail is stored in data
                               device=None, #What device is your tensor on
                               requires_grad=False #Wether or not track gradients with this tensors operations)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
###Getting information from tensors

Checking tensor dtype tensor.dype
Checking tensor shape tensor.shape
Checking tensor device tensor.device

In [ ]:
#Create Tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7346, 0.7640, 0.3735, 0.1923],
        [0.4466, 0.6480, 0.6161, 0.6410],
        [0.5790, 0.9898, 0.7261, 0.0550]])

In [ ]:
#Find out details
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device the tensor is on: {some_tensor.device}")

tensor([[0.7346, 0.7640, 0.3735, 0.1923],
        [0.4466, 0.6480, 0.6161, 0.6410],
        [0.5790, 0.9898, 0.7261, 0.0550]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device the tensor is on: cpu


###Manipulating Tensors

Tensor Operation include:

  *Addition
  *Subtraction
  *Multiplication
  *Division
  *Matrix Multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor += 10
tensor

tensor([11, 12, 13])

In [ ]:
tensor = torch.tensor([11, 12, 13])
tensor -= 10
tensor

tensor([1, 2, 3])

In [ ]:
tensor *= 10
tensor

tensor([10., 20., 30.])

In [ ]:
tensor = tensor / 10
tensor

tensor([1., 2., 3.])

In [ ]:
tensor1 = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]]])
tensor2 = torch.tensor([[[7, 8], [9,
                        10], [11, 12]]])
print(tensor1 * tensor1)
print(torch.matmul(tensor1,tensor2))
#This method is much faster than multiplying matrixes/tensors by hand

tensor([[[ 1,  4,  9],
         [16, 25, 36]]])
tensor([[[ 58,  64],
         [139, 154]]])


###How to deal With shape errors when multiplicating Matrixes

Inner dimensions must be the same
The resulting matrix will have the shape of the outer dimensions of the multiplied matrixes

In [ ]:
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
tensor2 = torch.tensor([[7, 8, 9],
                        [1, 2, 3]])
#Solution 1 Transpose second matrix if both shapes are equal
print(tensor1.shape)
print(tensor2.shape)

print(tensor2.T.shape)
print(torch.matmul(tensor1,tensor2.T))


torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[ 50,  14],
        [122,  32]])


###Finding min max mean and sum


In [ ]:
#Create tensor
x = torch.arange(0, 100, 10)
x, torch.min(x), x.min

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 tensor(0),
 <function Tensor.min>)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [ ]:
#argmin finds the index of the minimum value
#argmax does the same with the maximum
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
x[9]

tensor(90)

###Reshaping, Stacking, squeezing and unsqueezing tensors

Reshape - Reshapes an input tensor to a defined type


view - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor


Stacking - Combine multiple tensors on top of each other (vstack) or side by side


Squeeze - removes all '1' dimensions from a tensor


Unsqueeze - adds a '1' dimension to a tensor

Permute - Return a view of the input dimensions permutted in a certain way




In [ ]:
#Let's create tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x (because a view of a tensor shares the same memory as the original one)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#Squeeze removes all '1' dimensions from the tensor

print(f"\nPrevious tensor: {x_reshaped}")
print(f"Previous shape {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape {x_squeezed.shape}")



Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape torch.Size([9])


In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"\nPrevious target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape {x_unsqueezed.shape}")



Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape torch.Size([9, 1])


In [ ]:
#torch.permute() rearanges the dimensions of a target in a specific order

x_original = torch.rand(size=(224, 224, 3)) # Height width colour_channels RGB

#Permute the original tensor to rearange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #2->0, 0->1, 1->2
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

# Again the original and the permuted share the same memory even though they're different views

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


####Indexing selecting data from tensors

Inndexing in Pytorch is similar to indexing with NumPy

In [ ]:
#Creaye a tensor
import torch
x= torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Let's index in most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
#You can also use ":" to select all of target dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Values of the 0 dimension but only 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#Index to return 9
print(x[0, 2, 2])

#Index to return 3 6 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## Pytorch tensors and Numpy

Numpy is a popular scientific Python numerical computing library


Pytorch has a functionality to interact with it


*Data in NumPy wanted in Pytorch tensor -> torch.from_numpy(ndarray)


Pytorch tensor -> NumPy -> torch.Tensor.numpy()


In [ ]:
#Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #Warning when converting dtype will be float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
#Change value of array

array += 1
array, tensor

#Do not share the same memory adress

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
#Warning when converting dtype will be float32

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor what happens to array?

tensor += 1
tensor, numpy_tensor

#In this case yes they share the same memory location

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

##Reproductibility (trying to take out of random)

Is short how a neural network learns:

starts with random numbers -> tensor operations -> update the numbers and make them better representations -> repeat


to reduce the randomness of NN and Pytorch comes teh concept of a **random seed**

Potentially what the random seed does is "favour" the randomness

In [ ]:
import torch

#Create two random tensors
rand_tens_A = torch.rand(3, 3)
rand_tens_B = torch.rand(3, 3)

print(rand_tens_A)
print(rand_tens_B)
print(rand_tens_A == rand_tens_B)

tensor([[0.2694, 0.1856, 0.8733],
        [0.3960, 0.1815, 0.2945],
        [0.7683, 0.0923, 0.4922]])
tensor([[0.3469, 0.4479, 0.0534],
        [0.2062, 0.7491, 0.2049],
        [0.3883, 0.4550, 0.8851]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [ ]:
#Let's make some random but reproducible tensors

import torch

#set thed random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

#Manual seed it works only for one line code

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducebility:https://pytorch.org/docs/stable/notes/randomness.html


## Running tensors and Pytorch on the GPUS (and making faster computations)

GPUs = faster computations, thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes



### 1. Getting a GPU

1. Easiest Use Google collab for free (options to upgrade as well)
2. Use your own GPU (Purchase one)
3. Use clod computing GPC, AWS, Azure

For 2, 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up. Pytorch documentation:

In [ ]:
!nvidia-smi

Thu Dec 21 11:41:44 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
#Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

Since Pyorch can run in GPUs and CPUs it's bestpractice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

Run on GPU if available else run on CPU

## 3. Putting tensors and models on GPU

The reason is  because using GPUs results in faster computations

In [ ]:
#Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

###4. Moving tensors back to the CPU



In [ ]:
#If the tensor is in the GPU can't transform to NumPy

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])